site:
  title: devonfw
  url: https://devonfw.com/docs
content:
  sources: 
  - url: https://github.com/devonfw/java
    branches: HEAD
  - url: https://github.com/devonfw/typescript
    branches: HEAD
ui: 
  bundle:
    url: https://github.com/devonfw/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
output: 
  dir: ./target/generated-docs/docs
urls: 
  latest_version_segment: current
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en]
asciidoc:
  extensions:
  - "./extensions/tabs.js" 
  - "asciidoctor-external-callout"
  - asciidoctor-kroki
