name: Dispcher event on update of devonfw guide
env:
  BUILD_USER: ${{ secrets.BUILD_USER }}
  BUILD_USER_EMAIL:  ${{ secrets.BUILD_USER_EMAIL }}
on:
  push:
    branches: [ develop ]
  repository_dispatch:
    types: [dispatch-update-website]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup git user
        run: |
          git config --global user.email ${BUILD_USER_EMAIL}
          git config --global user.name ${BUILD_USER}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: update latest changes of devonfw-guide
        run: |
          cd devonfw-guide/
          git checkout master
          git fetch
          git branch
          git merge origin/master
          cd ..
          git add devonfw-guide
          cd katacoda-scenarios/
          git checkout master
          git fetch
          git branch
          git merge origin/master
          cd ..
          git add katacoda-scenarios
          cd wiki-tutorials/
          git checkout master
          git fetch
          git branch
          git merge origin/master
          cd ..
          git add wiki-tutorials
          cd architectures/
          git checkout master
          git fetch
          git branch
          git merge origin/master
          cd ..
          git add architectures
          git commit -m "[DocUpdate]"
          git push origin develop
