name: Broken link check

on:
  workflow_run:
    workflows: ["build-and-deploy"]
    types:
      - completed



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install linkchecker
        run: sudo apt-get install linkchecker
      - name: start check
        run: linkchecker https://devonfw.com 
